apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: "kubescape-c-0056-configured-liveliness-probes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments","replicasets","daemonsets","statefulsets"]
  validations:
    - expression: "object.kind != 'Pod' || object.spec.containers.all(container, has(container.livenessProbe))"
      message: "Pods must have livenessProbe set up (see more at https://hub.armosec.io/docs/c-0056)"
    - expression: "['Deployment','ReplicaSet','DaemonSet','StatefulSet'].all(kind, object.kind != kind) || object.spec.template.spec.containers.all(container, has(container.livenessProbe))"
      message: "Workloads must have livenessProbe set up (see more at https://hub.armosec.io/docs/c-0056)"