name: "main-policy-automation"
on:
  pull_request:
    types:
      [ opened, synchronize, reopened ]
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test-all-policies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: start minikube
      id: minikube
      uses: slashben/setup-minikube@master
      with:
          feature-gates: 'ValidatingAdmissionPolicy=true'
          extra-config: 'apiserver.runtime-config=admissionregistration.k8s.io/v1alpha1'
          kubernetes-version: 1.26.0
          container-runtime: containerd
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: azure/setup-kubectl@v3
    - run: |
        ./scripts/run-all-control-tests.sh

