name: "main-policy-automation"
on:
  pull_request:
    types:
      [ opened, synchronize, reopened ]
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/workflow/release.yaml'

jobs:
  test-all-policies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: start minikube
      id: minikube
      uses: slashben/setup-minikube@master
      with:
          feature-gates: 'ValidatingAdmissionPolicy=true'
          extra-config: 'apiserver.runtime-config=admissionregistration.k8s.io/v1beta1'
          kubernetes-version: v1.28.0-rc.1
          container-runtime: containerd
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: azure/setup-kubectl@v3
    - name: Running all control policy tests
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        ./scripts/run-all-control-tests.sh

