name: "Release"
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "release-v*"

jobs:
    
  release:
    #needs: test-all-policies
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Verify release tagged commit is on main
        run: |
          git fetch origin main
          git merge-base --is-ancestor ${GITHUB_REF##*/} origin/main && echo "${GITHUB_REF##*/} is a commit on main!"
      - name: Create release artifacts
        run: |
          mkdir release
          ./scripts/create-release-objects.sh release      
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.GITHUB_REF_NAME }}"
          release_name: "Release ${{ env.GITHUB_REF_NAME }}"
          draft: false
          prerelease: false
      - name: Publish release artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release
          asset_name: kubescape-validating-admission-policies.yaml
          asset_content_type: text/yaml